//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _PALOUT2_H_
#define _PALOUT2_H_

#include <TinyCLR_Interop.h>


extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_palout2;

#endif  //_PALOUT2_H_
